let deAlert1 = "Vor einer Auswertung müssen alle ";
let deAlert2 = " Atome gesetzt sein!";
let engAlert1 = "Before an evaluation all ";
let engAlert2 = " atoms must be set!";
let deAlert3 = "Es sind bereits ";
let deAlert4 = " Atome gesetzt!"
let engAlert3 = "There are already ";
let engAlert4 = " atoms set!"
let deAtoms = "Atome: ";
let engAtoms = "Atoms: ";
let deTrials = "Versuche: ";
let engTrials = "Trials: ";
let dePoints = "Punkte: ";
let engPoints = "Points: ";
let deScore = "Ergebnis: ";
let engScore = "Score: ";
let deHits = "Richtig: ";
let engHits = "Correct: ";
let deMissed = "Falsch: ";
let engMissed = "Incorrect: ";

