let deAlert1 = "Vor einer Auswertung müssen alle ";
let deAlert2 = " Atome gesetzt sein!";
let engAlert1 = "Before an evaluation all ";
let engAlert2 = " atoms must be set!";
let deAlert3 = "Es sind bereits ";
let deAlert4 = " Atome gesetzt!"
let engAlert3 = "There are already ";
let engAlert4 = " atoms set!";
let deAlert5 = "Das Ändern der Atomanzahl ist nach Spielbeginn nicht mehr möglich!";
let engAlert5 = "Changing the number of atoms is not possible after the game has started!";
let deAlert6 = "Das Ändern der Anzeigeart der Strahldurchgänge ist nach Spielbeginn nicht mehr möglich!";
let engAlert6 = "Changing the display type of the beam passes is not possible after the start of the game!";
let deAtoms = "Atome: ";
let engAtoms = "Atoms: ";
let deTrials = "Versuche: ";
let engTrials = "Trials: ";
let dePoints = "Punkte: ";
let engPoints = "Points: ";
let deScore = "Ergebnis: ";
let engScore = "Score: ";
let deHits = "Richtig: ";
let engHits = "Correct: ";
let deMissed = "Falsch: ";
let engMissed = "Incorrect: ";

